---
stages:
- name: BuildStage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: BuildJob
    type: builder
- name: DeployStage
  inputs:
  - type: job
    stage: BuildStage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: DeployJob
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
